namespace Registration_training
{
    public enum Componentes : int
    {
        Calculo_Vetorial = 0,
        Calculo_1 = 1,
        Calculo_2 = 2,
        Calculo_3 = 3,
        Introducao_Algebra_Linear = 4,
        Series_Diferenciais = 5,
        Calculo_Numerico = 6,
        Introducao_Engenharia_Computacao = 7,
        Materiais = 8,
        Metodologia = 9,
        Introducao_Programação = 10,
        Linguagem_Programação_1 = 11,
        Linguagem_Programação_2 = 12,
        Eletricidade_Circuitos_1 = 13,
        Eletricidade_Circuitos_2 = 14,
        Fisica_Aplicada = 15,
        Fisica_Experimental = 16,
        Circuitos_Logicos_1 = 17,
        Circuitos_Logicos_2 = 18,
        Pesquisa_Aplicada = 19,
        Mecanica_Para_Engenharia = 20,
        Calculo_Probabilidade = 21,
        Estrutura_Dados = 22,
        Eletronica_Aplicada_1 = 23,
        Eletronica_Aplicada_2 = 24,
        Arquitetura_Computadores = 25,
        Banco_Dados = 26,
        Analise_Projeto = 27,
        Introducao_Microeletronica = 28,
        Introducao_Mecanica_Fluidos = 29,
        Microcontroladores = 30,
        Sinais_Sitemas = 31,
        Sistemas_Operacionais = 32,
        Pesquisa_Operacional = 33,
        Engenharia_Software = 34,
        Redes_Computadores = 35,
        Redes_Sem_Fio = 36,
        Introducao_Computacao_Grafica = 37,
        Introducao_Processamento_Imagens = 38,
        Sistemas_Controle = 39,
        Avaliacao_Desempenho_Sistema = 40,
        Introducao_Teoria_Informacao = 41,
        Introducao_Inteligencia_Artificial = 42,
        Consepcao_Estruturada = 43,
        Robotica = 44,
        ADM_Engenharia = 45,
        Economia = 46,
        Computadores_Sociedade = 47,
        Estagio_Supervisionado = 48,
        TCC_1 = 49,
        TCC_2 = 50
    }
}
